#!/bin/bash

RESULT_CODE=0
export TZ=Europe/Prague

# run server
(cd dist && node server.js)&

# get local IP
dev=`ip route | awk '/default via/ { print $5 }'`
export QA_PRODUCT_HOST=`ip addr show "$dev" | awk '/^  *inet / {gsub("/.*", "", $2); print $2}' | head -n 1`
echo "QA_PRODUCT_HOST=$QA_PRODUCT_HOST"


# run tests
cd "$HOME/$CIRCLE_PROJECT_REPONAME/test-ui"
docker run -d -p 4444:4444 docker.salsitasoft.com/service-test:0.4
sleep 5

sed -i "s/^base_url=.*/base_url=http:\/\/$QA_PRODUCT_HOST:3000/" config/server_config.properties

#docker run -v `pwd`:/app docker.salsitasoft.com/shishito:0.1 shishito `id -u` `id -g` --test_rail "$TEST_RAIL_CRED" || RESULT_CODE=1
docker run -v `pwd`:/app docker.salsitasoft.com/shishito:0.1 shishito `id -u` `id -g` || RESULT_CODE=1
mkdir -p "$CIRCLE_TEST_REPORTS" && cp -r "$HOME/$CIRCLE_PROJECT_REPONAME/test-ui/results/"2* "$CIRCLE_TEST_REPORTS"/gui-results
exit "$RESULT_CODE"
