#!/bin/bash

RESULT_CODE=0
export TZ=Europe/Prague

# run server
(cd dist && node server.js)&

# run tests
cd "$HOME/$CIRCLE_PROJECT_REPONAME/test-ui"
#docker run -v `pwd`:/app docker.salsitasoft.com/shishito:0.1 shishito `id -u` `id -g` --test_rail "$TEST_RAIL_CRED" || RESULT_CODE=1
docker run -v `pwd`:/app docker.salsitasoft.com/shishito:0.1 shishito `id -u` `id -g` || RESULT_CODE=1
mkdir -p "$CIRCLE_TEST_REPORTS" && cp -r "$HOME/$CIRCLE_PROJECT_REPONAME/test-ui/results/"2* "$CIRCLE_TEST_REPORTS"/gui-results
exit "$RESULT_CODE"
